export const GLOBAL_EVENTS = {
  UPDATE_ALL: "UPDATE_ALL",
  AUTH_STATE_CHANGED: "AUTH_STATE_CHANGED",
  AUTH_STATE_CHANGED_FINISHED: "AUTH_STATE_CHANGED_FINISHED",
  ENQUEUE_MODAL: "ENQUEUE_MODAL",
}

export const TEST_EVENTS = {
  AUTH_STATE_CHANGED: "AUTH_STATE_CHANGED",
  ANALYTICS_INTERVAL_FIRED: "ANALYTICS_INTERVAL_FIRED",
}
