export type ModuleId =
  | "stabilize"
  | "body_downshift"
  | "cognitive_aid"
  | "attachment"
  | "no_contact"
  | "identity"
  | "narrative"
  | "boundaries"
  | "joy_competence"
  | "dating_ready"
  | "maintenance"
  | "mini_interventions"
  | "special_cases"
