import { IMood } from "./IMood"
import { MoodCategory } from "./MoodCategory"

enum MoodId {
  Anxious = "anxious",
  Sad = "sad",
  Stressed = "stressed",
  Angry = "angry",
  Frustrated = "frustrated",
  Lonely = "lonely",
  Depressed = "depressed",
  Hopeless = "hopeless",
  Fearful = "fearful",
  Guilty = "guilty",
  Overwhelmed = "overwhelmed",
  Disgusted = "disgusted",
  Empty = "empty",
  Helpless = "helpless",
  Heartbroken = "heartbroken",
  Bored = "bored",
  Happy = "happy",
  Content = "content",
  Calm = "calm",
  Alert = "alert",
  Curious = "curious",
  Reflective = "reflective",
  Indifferent = "indifferent",
  Balanced = "balanced",
  Focused = "focused",
  Joyful = "joyful",
  Grateful = "grateful",
  Peaceful = "peaceful",
  Motivated = "motivated",
  Inspired = "inspired",
  Confident = "confident",
  Hopeful = "hopeful",
  Excited = "excited",
  Optimistic = "optimistic",
  Nostalgic = "nostalgic",
  Relaxed = "relaxed",
  Satisfied = "satisfied",
  Indecisive = "indecisive",
  Reserved = "reserved",
  Apathetic = "apathetic",
  Surprised = "surprised",
  Detached = "detached",
}

const MOODS: Record<MoodId, IMood> = {
  [MoodId.Hopeless]: { title: "hopeless", category: MoodCategory.Negative },
  [MoodId.Fearful]: { title: "fearful", category: MoodCategory.Negative },
  [MoodId.Depressed]: { title: "depressed", category: MoodCategory.Negative },
  [MoodId.Sad]: { title: "sad", category: MoodCategory.Negative },
  [MoodId.Stressed]: { title: "stressed", category: MoodCategory.Negative },
  [MoodId.Anxious]: { title: "anxious", category: MoodCategory.Negative },
  [MoodId.Angry]: { title: "angry", category: MoodCategory.Negative },
  [MoodId.Frustrated]: { title: "frustrated", category: MoodCategory.Negative },
  [MoodId.Lonely]: { title: "lonely", category: MoodCategory.Negative },
  [MoodId.Overwhelmed]: { title: "overwhelmed", category: MoodCategory.Negative },
  [MoodId.Guilty]: { title: "guilty", category: MoodCategory.Negative },
  [MoodId.Empty]: { title: "empty", category: MoodCategory.Negative },
  [MoodId.Disgusted]: { title: "disgusted", category: MoodCategory.Negative },
  [MoodId.Helpless]: { title: "helpless", category: MoodCategory.Negative },
  [MoodId.Heartbroken]: { title: "heartbroken", category: MoodCategory.Negative },
  [MoodId.Happy]: { title: "happy", category: MoodCategory.Positive },
  [MoodId.Content]: { title: "content", category: MoodCategory.Positive },
  [MoodId.Calm]: { title: "calm", category: MoodCategory.Positive },
  [MoodId.Balanced]: { title: "balanced", category: MoodCategory.Positive },
  [MoodId.Focused]: { title: "focused", category: MoodCategory.Positive },
  [MoodId.Joyful]: { title: "joyful", category: MoodCategory.Positive },
  [MoodId.Grateful]: { title: "grateful", category: MoodCategory.Positive },
  [MoodId.Peaceful]: { title: "peaceful", category: MoodCategory.Positive },
  [MoodId.Motivated]: { title: "motivated", category: MoodCategory.Positive },
  [MoodId.Inspired]: { title: "inspired", category: MoodCategory.Positive },
  [MoodId.Confident]: { title: "confident", category: MoodCategory.Positive },
  [MoodId.Hopeful]: { title: "hopeful", category: MoodCategory.Positive },
  [MoodId.Excited]: { title: "excited", category: MoodCategory.Positive },
  [MoodId.Optimistic]: { title: "optimistic", category: MoodCategory.Positive },
  [MoodId.Relaxed]: { title: "relaxed", category: MoodCategory.Positive },
  [MoodId.Satisfied]: { title: "satisfied", category: MoodCategory.Positive },
  [MoodId.Bored]: { title: "bored", category: MoodCategory.Neutral },
  [MoodId.Alert]: { title: "alert", category: MoodCategory.Neutral },
  [MoodId.Curious]: { title: "curious", category: MoodCategory.Neutral },
  [MoodId.Reflective]: { title: "reflective", category: MoodCategory.Neutral },
  [MoodId.Indifferent]: { title: "indifferent", category: MoodCategory.Neutral },
  [MoodId.Nostalgic]: { title: "nostalgic", category: MoodCategory.Neutral },
  [MoodId.Indecisive]: { title: "indecisive", category: MoodCategory.Neutral },
  [MoodId.Reserved]: { title: "reserved", category: MoodCategory.Neutral },
  [MoodId.Apathetic]: { title: "apathetic", category: MoodCategory.Neutral },
  [MoodId.Surprised]: { title: "surprised", category: MoodCategory.Neutral },
  [MoodId.Detached]: { title: "detached", category: MoodCategory.Neutral },
}

const MOOD_TO_EMOJI: Record<MoodId, string> = {
  [MoodId.Hopeless]: "😟",
  [MoodId.Fearful]: "😨",
  [MoodId.Anxious]: "😰",
  [MoodId.Sad]: "😢",
  [MoodId.Stressed]: "😓",
  [MoodId.Angry]: "😠",
  [MoodId.Frustrated]: "😤",
  [MoodId.Lonely]: "😔",
  [MoodId.Depressed]: "😞",
  [MoodId.Guilty]: "😖",
  [MoodId.Overwhelmed]: "😵",
  [MoodId.Disgusted]: "🤢",
  [MoodId.Empty]: "😕",
  [MoodId.Bored]: "😴",
  [MoodId.Helpless]: "🤲",
  [MoodId.Heartbroken]: "💔",
  [MoodId.Happy]: "😄",
  [MoodId.Content]: "😐",
  [MoodId.Calm]: "😊",
  [MoodId.Alert]: "👁️",
  [MoodId.Curious]: "🤔",
  [MoodId.Reflective]: "🤨",
  [MoodId.Indifferent]: "😑",
  [MoodId.Balanced]: "⚖️",
  [MoodId.Focused]: "🧐",
  [MoodId.Joyful]: "🙂",
  [MoodId.Grateful]: "🙏",
  [MoodId.Peaceful]: "😌",
  [MoodId.Motivated]: "💪",
  [MoodId.Inspired]: "✨",
  [MoodId.Confident]: "😎",
  [MoodId.Hopeful]: "🌱",
  [MoodId.Excited]: "🤩",
  [MoodId.Optimistic]: "🌈",
  [MoodId.Relaxed]: "🧘",
  [MoodId.Satisfied]: "😋",
  [MoodId.Nostalgic]: "🕰️",
  [MoodId.Indecisive]: "🤷",
  [MoodId.Reserved]: "🤐",
  [MoodId.Apathetic]: "😒",
  [MoodId.Surprised]: "😲",
  [MoodId.Detached]: "😶",
}

const ALL_MOODS: MoodId[] = Object.keys(MOODS) as MoodId[]

export { MoodId, MOODS, MOOD_TO_EMOJI, ALL_MOODS }
