#!/bin/bash

# File name
FILE="./app.config.ts"

# Check if the file exists
if [ ! -f "$FILE" ]; then
    echo "Error: File $FILE does not exist."
    exit 1
fi

# Read the current versionCode
versionCode=$(grep 'versionCode' "$FILE" | awk -F': ' '{ print $2 }' | awk '{ print $1 }' | tr -d ',')

# Check if the versionCode was successfully read
if [ -z "$versionCode" ]; then
    echo "Error: Unable to read versionCode from $FILE."
    exit 1
fi

# Check if versionCode is a number
if ! [[ $versionCode =~ ^[0-9]+$ ]]; then
    echo "Error: versionCode in $FILE is not a valid number."
    exit 1
fi

# Increment the versionCode
let "versionCode++"

# Update versionCode in app.config.ts using awk
awk -v new_vc="$versionCode" '/versionCode:/ {sub(/[0-9]+/, new_vc)}1' "$FILE" > "${FILE}.tmp"

# Check if the awk command succeeded
if [ $? -ne 0 ]; then
    echo "Error: Failed to update versionCode in $FILE."
    exit 1
fi

# Replace the original file with the updated file
if ! mv "${FILE}.tmp" "$FILE"; then
    echo "Error: Failed to update $FILE with new versionCode."
    exit 1
fi

echo "Updated Android versionCode to $versionCode"
