#!/bin/bash

# File name
FILE="./app.config.ts"

# Check if the file exists
if [ ! -f "$FILE" ]; then
    echo "Error: File $FILE does not exist."
    exit 1
fi

# Read the current buildNumber under the ios property
buildNumber=$(awk -F '"' '/buildNumber:/ {print $2}' "$FILE")

# Check if the buildNumber was successfully read
if [ -z "$buildNumber" ]; then
    echo "Error: Unable to read buildNumber from $FILE."
    exit 1
fi

# Check if buildNumber is a number and increment it
if [[ $buildNumber =~ ^[0-9]+$ ]]; then
    ((buildNumber++))
else
    echo "Error: buildNumber in $FILE is not a valid number."
    exit 1
fi

# Read the current version
version=$(awk -F '"' '/version:/ {print $2}' "$FILE")

# Prompt user to update version number
echo "The current version number is $version. Do you want to update the version number? (yes/no or y/n)"
read -r update_version

# Normalize user input to lower case and check for 'yes' or 'y'
case "$update_version" in
    [yY]|[yY][eE][sS])
        update_version="yes"
        ;;
    *)
        update_version="no"
        ;;
esac

new_version=$version  # default to current version unless updated

# Check and update version if requested
if [ "$update_version" == "yes" ]; then
    IFS='.' read -r major minor patch <<< "$version"
    if [[ $patch =~ ^[0-9]+$ ]]; then
        ((patch++))
        new_version="$major.$minor.$patch"
    else
        echo "Error: PATCH version in $FILE is not a valid number."
        exit 1
    fi
fi

# Update buildNumber and optionally version in app.config.ts using awk
awk -v new_build="$buildNumber" -v new_ver="$new_version" 'BEGIN {FS=OFS="\""} /buildNumber:/ {$2=new_build} /version:/ && !seen {seen=1; $2=new_ver} 1' "$FILE" > "${FILE}.tmp"

# Check if the awk command succeeded
if [ $? -ne 0 ]; then
    echo "Error: Failed to update $FILE."
    exit 1
fi

# Replace the original file with the updated file
if mv "${FILE}.tmp" "$FILE"; then
    echo "Updated iOS buildNumber to $buildNumber"
    if [ "$update_version" == "yes" ]; then
        echo "and version to $new_version"
    fi
else
    echo "Error: Failed to update $FILE with new buildNumber and version."
    exit 1
fi
