enum Activity {
  Exercise = "exercise",
  Meditation = "meditation",
  Yoga = "yoga",
  Reading = "reading",
  Writing = "writing",
  Painting = "painting",
  Cooking = "cooking",
  Cleaning = "cleaning",
  Driving = "driving",
  Working = "working",
  Gaming = "gaming",
  Socializing = "socializing",
  WatchingTV = "watching_tv",
  Music = "music",
  Nature = "nature",
  Studying = "studying",
  Shopping = "shopping",
  Traveling = "traveling",
  BedRotting = "bedrotting",
  Eating = "eating",
  DrinkingCoffee = "drinking_coffee",
  PetTime = "pet_time",
  Other = "other",
}

const ACTIVITY_TO_EMOJI: Record<Activity, string> = {
  [Activity.Exercise]: "🏃",
  [Activity.Meditation]: "🧘",
  [Activity.Yoga]: "🧘",
  [Activity.Reading]: "📚",
  [Activity.Writing]: "✍️",
  [Activity.Painting]: "🎨",
  [Activity.Cooking]: "👨‍🍳",
  [Activity.Cleaning]: "🧹",
  [Activity.Driving]: "🚗",
  [Activity.Working]: "💼",
  [Activity.Gaming]: "🎮",
  [Activity.Socializing]: "🗣️",
  [Activity.WatchingTV]: "📺",
  [Activity.Music]: "🎵",
  [Activity.Nature]: "🌿",
  [Activity.Studying]: "📝",
  [Activity.Shopping]: "🛍️",
  [Activity.Traveling]: "✈️",
  [Activity.BedRotting]: "🛏️",
  [Activity.Eating]: "🍽️",
  [Activity.DrinkingCoffee]: "☕",
  [Activity.PetTime]: "🐶",
  [Activity.Other]: "✨",
}

const ALL_ACTIVITIES: Activity[] = Object.values(Activity) as Activity[]

export { Activity, ACTIVITY_TO_EMOJI, ALL_ACTIVITIES }
